# Loaded under /niryo_robot
joint_state_controller:
  type: "joint_state_controller/JointStateController"
  publish_rate: 100

arm_controller:
  type: "position_controllers/JointTrajectoryController"
  joints: [joint_1, joint_2, joint_3, joint_4, joint_5, joint_6]
  constraints:
    goal_time: 1.0
    stopped_velocity_tolerance: 0.01
    joint_1: {trajectory: 0.05, goal: 0.02}
    joint_2: {trajectory: 0.05, goal: 0.02}
    joint_3: {trajectory: 0.05, goal: 0.02}
    joint_4: {trajectory: 0.05, goal: 0.02}
    joint_5: {trajectory: 0.05, goal: 0.02}
    joint_6: {trajectory: 0.05, goal: 0.02}
  state_publish_rate: 100
  action_monitor_rate: 20
  allow_partial_joints_goal: false
  stop_trajectory_duration: 0.0
