moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager

controller_list:
  - name: /niryo_robot/arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: true
    joints:
      - joint_1
      - joint_2
      - joint_3
      - joint_4
      - joint_5
      - joint_6
